server:
  port: 9002

spring:
  application:
    name: service-discover-c

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
feign:
  httpclient:
    connection-timeout: 6000
  hystrix:
    enabled: true
